<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container-fluid">
		<div class="navbar-header">
            	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            		<span class="icon-bar"></span>
            		<span class="icon-bar"></span>
            		<span class="icon-bar"></span>                        
            	</button>
            	<p class="navbar-brand">Internet of Things</p>
        	</div>
        		<div class="collapse navbar-collapse" id="myNavbar">
            	<ul class="nav navbar-nav">
            	<li class="dropdown">
            	<li class="active"><a href="index.html">Index</a></li>
            	<li><a href="topic.html">Topic</a></li>
            	<li><a href="quiz.html">Quiz</a></li>
            	</ul>
            	<ul class="nav navbar-nav navbar-right">
            	<li><a href="enhancements.html"><span class="glyphicon glyphicon-info-sign"></span> Enhancements</a></li>
            	</ul>
        	</div>

        </div>
</nav>
<header id="all_quiz">
    <img id="logo" src="images/iotlogo.png" alt="IoT Logo">
    <br>
    <h1 class="head1">Internet <sup>of</sup> Things</h1>
</header>